In [2]:
import torch

In [4]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [19]:
X=torch.arange(18).reshape(2,9)
Y=X.clone()
Y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [28]:
x=X.sum(axis=1)#沿着一个轴计算，如axis=0则按行相加
#axis=？则将第？维的数删掉
x,x.shape

(tensor([ 36, 117]), torch.Size([2]))

In [55]:
#沿两个维度求和,最后求和得到的矩阵形如未等于的其他维度
A=torch.arange(20*2,dtype=int).reshape(2,5,2,2)
A.shape,A
A=A.float()

In [57]:
x=A.sum(axis=[0,1])

x.shape,A.mean()

(torch.Size([2, 2]), tensor(19.5000))

In [58]:
A

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]],

         [[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]],

         [[16., 17.],
          [18., 19.]]],


        [[[20., 21.],
          [22., 23.]],

         [[24., 25.],
          [26., 27.]],

         [[28., 29.],
          [30., 31.]],

         [[32., 33.],
          [34., 35.]],

         [[36., 37.],
          [38., 39.]]]])

In [61]:
#我们可以(通过广播将A除以sum_A),那么前提就是在调用函数sum时保持轴数不变
sum_A=A.sum(axis=1,keepdims=True)
sum_A,sum_A.shape,A.shape

(tensor([[[[ 40.,  45.],
           [ 50.,  55.]]],
 
 
         [[[140., 145.],
           [150., 155.]]]]),
 torch.Size([2, 1, 2, 2]),
 torch.Size([2, 5, 2, 2]))

In [78]:
#点积dot product
#要注意两个向量的点积要保证数据类型dtype相同
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y),torch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [79]:
#线性代数中最有用的一些运算符是范数（norm）。 非正式地说，向量的范数是表示一个向量有多大。 这里考虑的大小（size）概念不涉及维度，而是分量的大小。
#欧几里得距离是L2范数，更常用的是L1范数，表示为向量元素的绝对值之和

In [90]:
#L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [91]:
#L1范数,元素绝对值之和
torch.abs(u).sum()

tensor(7.)

In [92]:
#对于矩阵
#frobenius norm佛罗贝尼斯范数
#[矩阵](的Frobenius范数（Frobenius norm）是矩阵元素平方和的平方根：
torch.ones((3,4,9))
torch.norm(torch.ones((3,4,9)))

tensor(10.3923)

In [ ]:
#computing matrix
  