In [6]:
import torch

In [23]:
#arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

x=torch.arange(4.0,requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [24]:
#计算y关于x的梯度之前，需要一个地方来存储梯度
x.requires_grad_(True)
x.grad

In [30]:
y=2*torch.dot(x,x)
y


tensor(28., grad_fn=<MulBackward0>)

In [26]:
y.backward()#利用反向传播函数来自动计算y关于x的每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [33]:
#默认情况下pyTorch会进行梯度累积，需要清楚之前的值
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [34]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad


tensor([0., 2., 4., 6.])

In [36]:
#显示构造和隐式构造
